export const DATA_REQUEST = 'DATA_REQUEST';
export const DATA_SUCCESS = 'DATA_SUCCESS';
export const DATA_FAIL = 'DATA_FAIL';

export const N_DATA_REQUEST = 'N_DATA_REQUEST';
export const N_DATA_SUCCESS = 'N_DATA_SUCCESS';
export const N_DATA_FAIL = 'N_DATA_FAIL';


export const DEFAULT_DATA_REQUEST = 'DEFAULT_DATA_REQUEST';
export const DEFAULT_DATA_SUCCESS = 'DEFAULT_DATA_SUCCESS';
export const DEFAULT_DATA_FAIL = 'DEFAULT_DATA_FAIL';

export const DEFAULT_DATA_CSV_REQUEST = 'DEFAULT_DATA_CSV_REQUEST';
export const DEFAULT_DATA_CSV_SUCCESS = 'DEFAULT_DATA_CSV_SUCCESS';
export const DEFAULT_DATA_CSV_FAIL = 'DEFAULT_DATA_CSV_FAIL';